common: &common
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *common
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *common
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *common
  adapter: sqlite3
  database: db/production.sqlite3
